version: '3.8'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=ScraperDB
    ports:
      - "27017:27017"

  server:
    build: ./server
    environment:
      - NEST_CONFIG_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - ./client/dist:/usr/src/app/server
      - /usr/src/app/server/node_modules

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./server/dist:/usr/src/app/server
      - /usr/src/app/server/node_modules
